name: sushi_room
description: SushiRoom App
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  animated_theme_switcher: ^2.0.8
  get: ^4.6.6
  shared_preferences: ^2.2.1
  device_info_plus: ^9.0.3
  dynamic_color: ^1.6.6
  google_fonts: ^6.0.0
  permission_handler: ^11.0.0
  location: ^5.0.3
  app_settings: ^5.0.0
  animations: ^2.0.8
  mobile_scanner: ^3.4.1
  firebase_core: ^2.16.0
  firebase_auth: ^4.10.0
  firebase_database: ^10.2.6
  qr_flutter: ^4.1.0
  fluttertoast: ^8.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
